dist: focal
os: linux
language: python
addons:
  hosts:
    - rmq.amqpstorm.io
python:
  - 2.7
  - 3.6
  - 3.9
  - 3.10-dev
before_install:
  - docker build -t amqpstormdev ./docker/
  - docker run -d --hostname rmq.amqpstorm.io --name amqpstormdev -p 5671:5671 -p 5672:5672 -p 15671:15671 -p 15672:15672 amqpstormdev
  - docker cp amqpstormdev:/etc/rabbitmq/ssl/ ./amqpstorm/tests/resources/
  - docker exec amqpstormdev wait-for-rabbitmq
  - docker exec amqpstormdev rabbitmqctl add_user 'amqpstorm' '2a55f70a841f18b'
  - docker exec amqpstormdev rabbitmqctl -p / set_permissions 'amqpstorm' '.*' '.*' '.*'
  - docker exec amqpstormdev rabbitmqctl set_user_tags amqpstorm administrator
  - nc -zv rmq.amqpstorm.io 5671  || exit 1
  - nc -zv rmq.amqpstorm.io 5672  || exit 1
  - nc -zv rmq.amqpstorm.io 15671 || exit 1
  - nc -zv rmq.amqpstorm.io 15672 || exit 1
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  - pytest --cov=./amqpstorm --durations=5
  - flake8 --ignore=F821 .
after_success:
  - bash <(curl -s https://codecov.io/bash)
services:
  - docker
